# -*- coding: utf-8 -*-
"""01_data_generation_and_schema.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jQqotAEJ1f_cg_n9vU-TeKO25TWt6JxN
"""

import sqlite3
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

# Create SQLite database
conn = sqlite3.connect("operational_audit.db")
cursor = conn.cursor()

# Create tables
cursor.execute("""
CREATE TABLE vendors (
    vendor_id INTEGER PRIMARY KEY,
    vendor_name TEXT,
    contract_rate REAL
)
""")

cursor.execute("""
CREATE TABLE services (
    service_id INTEGER PRIMARY KEY,
    service_type TEXT,
    status TEXT,
    disconnect_date DATE
)
""")

cursor.execute("""
CREATE TABLE invoices (
    invoice_id INTEGER PRIMARY KEY,
    vendor_id INTEGER,
    service_id INTEGER,
    invoice_date DATE,
    billed_amount REAL,
    expected_amount REAL
)
""")

conn.commit()

# -----------------------------
# Generate Vendors
# -----------------------------
vendors = pd.DataFrame({
    "vendor_id": [1, 2, 3],
    "vendor_name": ["Alpha Networks", "Beta Solutions", "Gamma Telecom"],
    "contract_rate": [100.00, 95.00, 105.00]
})

vendors.to_sql("vendors", conn, if_exists="append", index=False)

# -----------------------------
# Generate Services
# -----------------------------
np.random.seed(42)

service_ids = range(1, 101)

services = []
for sid in service_ids:
    status = np.random.choice(["Active", "Disconnected"], p=[0.8, 0.2])
    disconnect_date = None

    if status == "Disconnected":
        disconnect_date = datetime.now() - timedelta(days=np.random.randint(30, 180))

    services.append([
        sid,
        np.random.choice(["Internet", "Voice", "Cloud"]),
        status,
        disconnect_date
    ])

services_df = pd.DataFrame(
    services,
    columns=["service_id", "service_type", "status", "disconnect_date"]
)

services_df.to_sql("services", conn, if_exists="append", index=False)

# -----------------------------
# Generate Invoices (12 months)
# -----------------------------
invoices = []
invoice_id = 1

for sid in service_ids:
    vendor_id = np.random.choice([1, 2, 3])
    base_rate = vendors.loc[vendors.vendor_id == vendor_id, "contract_rate"].values[0]

    for month_offset in range(12):
        invoice_date = datetime.now() - timedelta(days=30 * month_offset)

        # Inject overbilling
        billed_amount = base_rate * np.random.choice([1, 1, 1.1, 1.2])

        invoices.append([
            invoice_id,
            vendor_id,
            sid,
            invoice_date,
            billed_amount,
            base_rate
        ])

        invoice_id += 1

invoices_df = pd.DataFrame(
    invoices,
    columns=[
        "invoice_id",
        "vendor_id",
        "service_id",
        "invoice_date",
        "billed_amount",
        "expected_amount"
    ]
)

invoices_df.to_sql("invoices", conn, if_exists="append", index=False)

conn.commit()

pd.read_sql("SELECT * FROM invoices LIMIT 5", conn)

query = """
SELECT
    v.vendor_name,
    COUNT(*) AS overbilled_invoices,
    ROUND(SUM(i.billed_amount - i.expected_amount), 2) AS total_overbilled_amount
FROM invoices i
JOIN vendors v ON i.vendor_id = v.vendor_id
WHERE i.billed_amount > i.expected_amount
GROUP BY v.vendor_name
ORDER BY total_overbilled_amount DESC
"""

pd.read_sql(query, conn)

query = """
SELECT
    s.service_id,
    s.service_type,
    s.disconnect_date,
    i.invoice_date,
    i.billed_amount,
    v.vendor_name
FROM services s
JOIN invoices i ON s.service_id = i.service_id
JOIN vendors v ON i.vendor_id = v.vendor_id
WHERE s.status = 'Disconnected'
  AND i.invoice_date > s.disconnect_date
ORDER BY i.invoice_date DESC
"""

pd.read_sql(query, conn)

query = """
SELECT
    v.vendor_name,
    COUNT(*) AS post_disconnect_invoices,
    ROUND(SUM(i.billed_amount), 2) AS total_invalid_charges
FROM services s
JOIN invoices i ON s.service_id = i.service_id
JOIN vendors v ON i.vendor_id = v.vendor_id
WHERE s.status = 'Disconnected'
  AND i.invoice_date > s.disconnect_date
GROUP BY v.vendor_name
ORDER BY total_invalid_charges DESC
"""

pd.read_sql(query, conn)

query = """
SELECT
    strftime('%Y-%m', i.invoice_date) AS billing_month,
    ROUND(SUM(i.billed_amount - i.expected_amount), 2) AS overbilled_amount
FROM invoices i
WHERE i.billed_amount > i.expected_amount
GROUP BY billing_month
ORDER BY billing_month
"""

df_trends = pd.read_sql(query, conn)
df_trends

import matplotlib.pyplot as plt

plt.figure()
plt.plot(df_trends["billing_month"], df_trends["overbilled_amount"])
plt.xticks(rotation=45)
plt.title("Monthly Overbilled Amount Trend")
plt.tight_layout()
plt.show()

query = """
SELECT
    v.vendor_name,
    COUNT(DISTINCT i.invoice_id) AS total_invoices,
    SUM(CASE WHEN i.billed_amount > i.expected_amount THEN 1 ELSE 0 END) AS overbilled_count,
    ROUND(
        1.0 * SUM(CASE WHEN i.billed_amount > i.expected_amount THEN 1 ELSE 0 END)
        / COUNT(DISTINCT i.invoice_id),
        2
    ) AS risk_score
FROM invoices i
JOIN vendors v ON i.vendor_id = v.vendor_id
GROUP BY v.vendor_name
ORDER BY risk_score DESC
"""

pd.read_sql(query, conn)

# Export overbilling summary
overbilling_df = pd.read_sql("""
SELECT
    v.vendor_name,
    COUNT(*) AS overbilled_invoices,
    ROUND(SUM(i.billed_amount - i.expected_amount), 2) AS total_overbilled_amount
FROM invoices i
JOIN vendors v ON i.vendor_id = v.vendor_id
WHERE i.billed_amount > i.expected_amount
GROUP BY v.vendor_name
""", conn)

overbilling_df.to_csv("overbilling_summary.csv", index=False)

# Export post-disconnect billing
post_disconnect_df = pd.read_sql("""
SELECT
    s.service_id,
    s.service_type,
    s.disconnect_date,
    i.invoice_date,
    i.billed_amount,
    v.vendor_name
FROM services s
JOIN invoices i ON s.service_id = i.service_id
JOIN vendors v ON i.vendor_id = v.vendor_id
WHERE s.status = 'Disconnected'
  AND i.invoice_date > s.disconnect_date
""", conn)

post_disconnect_df.to_csv("post_disconnect_charges.csv", index=False)